---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: windows2012r2

suites:
  - name: default
    run_list:
      - recipe[windows-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
  - name: windows
    driver:
      box: addle/windows-server-2012-r2
    run_list:
      - recipe[windows-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
