---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows2012r2
    driver:
      box: mwrock/Windows2012R2
    transport:
      name: winrm
      elevated: true
suites:
  - name: windows
    run_list:
      - recipe[windows-cookbook::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
